### ISSUE TITLE
java.lang.IllegalStateException: Failed to resolve the class file version of the current VM: unknown java version: 0

### ISSUE THREAD

**Issue by sreepradha** [serenity-bdd/serenity-rest-starter#13]
The serenity rest starter works fine on my local machine but when i try the same codebase on an Amazon workspace, it throws an error saying "java.lang.IllegalStateException: Failed to resolve the class file version of the current VM: unknown java version: 0". The workspace has java, maven and eclipse everything with the same version as the local machine. I'm not able to recreate this error nor work around this error. Any suggestions would be helpful.

**Comment by nandhu88** [comment]
@sreepradha where you able to fix this issue? I aswell have the same issue

**Comment by wakaleo** [comment]
Hard to say, sounds like a JVM version-related issue

**Comment by sreepradha** [comment]
That’s right. The compiler was set to an older version of Java. Changing the version resolved the issue.

**Comment by akashdktyagi** [comment]
@sreepradha where did you made this change. I am facing the same but only with this project. What appears to be different here do not know. What did you change to make things work?

@wakaleo Can you check whats wrong here? This is not one off, multiple people facing the same. Other java maven projects working fine except this one. Can you please find out and guide what could be wrong here. I expect the examples to be working out of the box.

Here are the logs.

```
serenity-rest-starter $ mvn clean install
[WARNING] 
[WARNING] Some problems were encountered while building the effective settings
[WARNING] expected START_TAG or END_TAG not TEXT (position: TEXT seen ...TINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">\n\u200b\n<s... @7:3)  @ /Users/akashtyagi/.m2/settings.xml, line 7, column 3
[WARNING] 
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------< net.serenitybdd.starter:serenity-rest-starter >------------
[INFO] Building Sample Serenity BDD project using Cucumber 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ serenity-rest-starter ---
[INFO] Deleting /Users/akashtyagi/Documents/vCodePostDec2023/personal/trainings/serenity-rest-starter/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ serenity-rest-starter ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/akashtyagi/Documents/vCodePostDec2023/personal/trainings/serenity-rest-starter/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ serenity-rest-starter ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ serenity-rest-starter ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ serenity-rest-starter ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 4 source files to /Users/akashtyagi/Documents/vCodePostDec2023/personal/trainings/serenity-rest-starter/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ serenity-rest-starter ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ serenity-rest-starter ---
[WARNING] JAR will be empty - no content was marked for inclusion!
[INFO] Building jar: /Users/akashtyagi/Documents/vCodePostDec2023/personal/trainings/serenity-rest-starter/target/serenity-rest-starter-1.0.0-SNAPSHOT.jar
[INFO] 
[INFO] --- maven-failsafe-plugin:3.0.0-M5:integration-test (default) @ serenity-rest-starter ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
18:05:16.062 [pool-2-thread-1] INFO  i.c.core.plugin.SerenityReporter - Running feature from classpath:features/postcodes/looking_up_post_codes.feature

18:05:16.299 [pool-2-thread-1] INFO   - 

-------------------------------------------------------------------------------------
     _______. _______ .______       _______ .__   __.  __  .___________.____    ____ 
    /       ||   ____||   _  \     |   ____||  \ |  | |  | |           |\   \  /   / 
   |   (----`|  |__   |  |_)  |    |  |__   |   \|  | |  | `---|  |----` \   \/   /  
    \   \    |   __|  |      /     |   __|  |  . `  | |  |     |  |       \_    _/   
.----)   |   |  |____ |  |\  \----.|  |____ |  |\   | |  |     |  |         |  |     
|_______/    |_______|| _| `._____||_______||__| \__| |__|     |__|         |__|    
                                                                                     
 News and tutorials at http://www.serenity-bdd.info                                  
 Documentation at https://wakaleo.gitbooks.io/the-serenity-book/content/             
 Join the Serenity Community on Gitter: https://gitter.im/serenity-bdd/serenity-core 
 Serenity BDD Support and Training at http://serenity-bdd.info/#/trainingandsupport  
-------------------------------------------------------------------------------------


18:05:16.305 [pool-2-thread-1] INFO   - Test Suite Started: Looking up post codes

org.junit.runner.notification.StoppedByUserException
        at org.junit.runner.notification.RunNotifier.fireTestStarted(RunNotifier.java:151)
        at org.apache.maven.surefire.common.junit4.Notifier.fireTestStarted(Notifier.java:100)
        at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:133)
        at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:27)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at io.cucumber.junit.CucumberSerenityRunner.runChild(CucumberSerenityRunner.java:258)
        at io.cucumber.junit.CucumberSerenityRunner.runChild(CucumberSerenityRunner.java:57)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:405)
        at org.apache.maven.surefire.junitcore.pc.InvokerStrategy.schedule(InvokerStrategy.java:54)
        at org.apache.maven.surefire.junitcore.pc.Scheduler.schedule(Scheduler.java:362)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at io.cucumber.junit.CucumberSerenityRunner$RunCucumber.evaluate(CucumberSerenityRunner.java:286)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:405)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)



0 Scenarios

0 Steps

0m
0.568s





18:05:16.742 [pool-2-thread-1] INFO  i.c.core.plugin.SerenityReporter - Cleanup test resources for URI classpath:features/postcodes/looking_up_post_codes.feature

null
java.lang.IllegalStateException: Failed to resolve the class file version of the current VM: Unknown Java version: 0
        at net.bytebuddy.ClassFileVersion$VersionLocator$Unresolved.resolve(ClassFileVersion.java:558)
        at net.bytebuddy.ClassFileVersion.ofThisVm(ClassFileVersion.java:276)
        at net.bytebuddy.dynamic.loading.ClassInjector$UsingLookup.isAvailable(ClassInjector.java:1562)
        at net.thucydides.core.steps.StepFactory.<init>(StepFactory.java:73)
        at net.thucydides.core.steps.StepFactory.<init>(StepFactory.java:91)
        at net.thucydides.core.steps.StepFactory.lambda$static$0(StepFactory.java:55)
        at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:357)
        at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:225)
        at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:194)
        at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
        at net.thucydides.core.steps.StepFactory.getFactory(StepFactory.java:95)
        at net.thucydides.core.steps.StepEventBus.clear(StepEventBus.java:297)
        at io.cucumber.core.plugin.SerenityReporter.cleanupTestResourcesForURI(SerenityReporter.java:786)
        at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
        at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
        at io.cucumber.core.plugin.SerenityReporter.assureTestSuiteFinished(SerenityReporter.java:773)
        at io.cucumber.core.plugin.SerenityReporter.handleTestRunFinished(SerenityReporter.java:371)
        at io.cucumber.core.eventbus.AbstractEventPublisher.send(AbstractEventPublisher.java:51)
        at io.cucumber.core.eventbus.AbstractEventBus.send(AbstractEventBus.java:12)
        at io.cucumber.core.runtime.CucumberExecutionContext.emitTestRunFinished(CucumberExecutionContext.java:93)
        at io.cucumber.core.runtime.CucumberExecutionContext.finishTestRun(CucumberExecutionContext.java:74)
        at io.cucumber.junit.CucumberSerenityRunner$RunCucumber.evaluate(CucumberSerenityRunner.java:288)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:405)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)

[INFO] Running Looking up post codes

Scenario Outline: Looking up US locations by post code                 # features/postcodes/looking_up_post_codes.feature:8
18:05:16.479 [pool-2-thread-1] INFO  i.c.core.plugin.SerenityReporter - Running feature from classpath:features/postcodes/looking_up_post_codes.feature
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.296 s <<< FAILURE! - in Looking up post codes
[ERROR] Looking up post codes.Looking up US locations by post code #1  Time elapsed: 0.296 s  <<< ERROR!
java.lang.IllegalStateException: Failed to resolve the class file version of the current VM: Unknown Java version: 0

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   Failed to resolve the class file version of the current VM: Unknown Java version: 0
[INFO] 
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- serenity-maven-plugin:2.4.51:aggregate (serenity-reports) @ serenity-rest-starter ---
[INFO] Test results for 0 tests generated in 1.7 secs in directory: file:/Users/akashtyagi/Documents/vCodePostDec2023/personal/trainings/serenity-rest-starter/target/site/serenity/
[INFO] -----------------------------------------
[INFO]  SERENITY TESTS : SUCCESS
[INFO] -----------------------------------------
[INFO] | Tests executed         | 0
[INFO] | Tests passed           | 0
[INFO] | Tests failed           | 0
[INFO] | Tests with errors      | 0
[INFO] | Tests compromised      | 0
[INFO] | Tests pending          | 0
[INFO] | Tests ignored/skipped  | 0
[INFO] ------------------------ | --------------
[INFO] | Total Duration         | 000ms
[INFO] | Fastest test took      | 000ms
[INFO] | Slowest test took      | 000ms
[INFO] -----------------------------------------
[INFO] 
[INFO] SERENITY REPORTS
[INFO]   - Full Report: file:///Users/akashtyagi/Documents/vCodePostDec2023/personal/trainings/serenity-rest-starter/target/site/serenity/index.html
[INFO] 
[INFO] --- maven-failsafe-plugin:3.0.0-M5:verify (default) @ serenity-rest-starter ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  19.059 s
[INFO] Finished at: 2024-02-17T18:05:20+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:3.0.0-M5:verify (default) on project serenity-rest-starter: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/akashtyagi/Documents/vCodePostDec2023/personal/trainings/serenity-rest-starter/target/failsafe-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
serenity-rest-starter $ mvn clean install
[WARNING] 
[WARNING] Some problems were encountered while building the effective settings
[WARNING] expected START_TAG or END_TAG not TEXT (position: TEXT seen ...TINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">\n\u200b\n<s... @7:3)  @ /Users/akashtyagi/.m2/settings.xml, line 7, column 3
[WARNING] 
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------< net.serenitybdd.starter:serenity-rest-starter >------------
[INFO] Building Sample Serenity BDD project using Cucumber 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ serenity-rest-starter ---
[INFO] Deleting /Users/akashtyagi/Documents/vCodePostDec2023/personal/trainings/serenity-rest-starter/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ serenity-rest-starter ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/akashtyagi/Documents/vCodePostDec2023/personal/trainings/serenity-rest-starter/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ serenity-rest-starter ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ serenity-rest-starter ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ serenity-rest-starter ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 4 source files to /Users/akashtyagi/Documents/vCodePostDec2023/personal/trainings/serenity-rest-starter/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ serenity-rest-starter ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ serenity-rest-starter ---
[WARNING] JAR will be empty - no content was marked for inclusion!
[INFO] Building jar: /Users/akashtyagi/Documents/vCodePostDec2023/personal/trainings/serenity-rest-starter/target/serenity-rest-starter-1.0.0-SNAPSHOT.jar
[INFO] 
[INFO] --- maven-failsafe-plugin:3.0.0-M5:integration-test (default) @ serenity-rest-starter ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
18:06:55.815 [pool-2-thread-1] INFO  i.c.core.plugin.SerenityReporter - Running feature from classpath:features/postcodes/looking_up_post_codes.feature

18:06:55.984 [pool-2-thread-1] INFO   - 

-------------------------------------------------------------------------------------
     _______. _______ .______       _______ .__   __.  __  .___________.____    ____ 
    /       ||   ____||   _  \     |   ____||  \ |  | |  | |           |\   \  /   / 
   |   (----`|  |__   |  |_)  |    |  |__   |   \|  | |  | `---|  |----` \   \/   /  
    \   \    |   __|  |      /     |   __|  |  . `  | |  |     |  |       \_    _/   
.----)   |   |  |____ |  |\  \----.|  |____ |  |\   | |  |     |  |         |  |     
|_______/    |_______|| _| `._____||_______||__| \__| |__|     |__|         |__|    
                                                                                     
 News and tutorials at http://www.serenity-bdd.info                                  
 Documentation at https://wakaleo.gitbooks.io/the-serenity-book/content/             
 Join the Serenity Community on Gitter: https://gitter.im/serenity-bdd/serenity-core 
 Serenity BDD Support and Training at http://serenity-bdd.info/#/trainingandsupport  
-------------------------------------------------------------------------------------


18:06:55.988 [pool-2-thread-1] INFO   - Test Suite Started: Looking up post codes

org.junit.runner.notification.StoppedByUserException
        at org.junit.runner.notification.RunNotifier.fireTestStarted(RunNotifier.java:151)
        at org.apache.maven.surefire.common.junit4.Notifier.fireTestStarted(Notifier.java:100)
        at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:133)
        at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:27)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at io.cucumber.junit.CucumberSerenityRunner.runChild(CucumberSerenityRunner.java:258)
        at io.cucumber.junit.CucumberSerenityRunner.runChild(CucumberSerenityRunner.java:57)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:405)
        at org.apache.maven.surefire.junitcore.pc.InvokerStrategy.schedule(InvokerStrategy.java:54)
        at org.apache.maven.surefire.junitcore.pc.Scheduler.schedule(Scheduler.java:362)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at io.cucumber.junit.CucumberSerenityRunner$RunCucumber.evaluate(CucumberSerenityRunner.java:286)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:405)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)



0 Scenarios

0 Steps

0m
0.389s





18:06:56.278 [pool-2-thread-1] INFO  i.c.core.plugin.SerenityReporter - Cleanup test resources for URI classpath:features/postcodes/looking_up_post_codes.feature

null
java.lang.IllegalStateException: Failed to resolve the class file version of the current VM: Unknown Java version: 0
        at net.bytebuddy.ClassFileVersion$VersionLocator$Unresolved.resolve(ClassFileVersion.java:558)
        at net.bytebuddy.ClassFileVersion.ofThisVm(ClassFileVersion.java:276)
        at net.bytebuddy.dynamic.loading.ClassInjector$UsingLookup.isAvailable(ClassInjector.java:1562)
        at net.thucydides.core.steps.StepFactory.<init>(StepFactory.java:73)
        at net.thucydides.core.steps.StepFactory.<init>(StepFactory.java:91)
        at net.thucydides.core.steps.StepFactory.lambda$static$0(StepFactory.java:55)
        at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:357)
        at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:225)
        at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:194)
        at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
        at net.thucydides.core.steps.StepFactory.getFactory(StepFactory.java:95)
        at net.thucydides.core.steps.StepEventBus.clear(StepEventBus.java:297)
        at io.cucumber.core.plugin.SerenityReporter.cleanupTestResourcesForURI(SerenityReporter.java:786)
        at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
        at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
        at io.cucumber.core.plugin.SerenityReporter.assureTestSuiteFinished(SerenityReporter.java:773)
        at io.cucumber.core.plugin.SerenityReporter.handleTestRunFinished(SerenityReporter.java:371)
        at io.cucumber.core.eventbus.AbstractEventPublisher.send(AbstractEventPublisher.java:51)
        at io.cucumber.core.eventbus.AbstractEventBus.send(AbstractEventBus.java:12)
        at io.cucumber.core.runtime.CucumberExecutionContext.emitTestRunFinished(CucumberExecutionContext.java:93)
        at io.cucumber.core.runtime.CucumberExecutionContext.finishTestRun(CucumberExecutionContext.java:74)
        at io.cucumber.junit.CucumberSerenityRunner$RunCucumber.evaluate(CucumberSerenityRunner.java:288)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:405)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)

[INFO] Running Looking up post codes

Scenario Outline: Looking up US locations by post code                 # features/postcodes/looking_up_post_codes.feature:8
18:06:56.106 [pool-2-thread-1] INFO  i.c.core.plugin.SerenityReporter - Running feature from classpath:features/postcodes/looking_up_post_codes.feature
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.191 s <<< FAILURE! - in Looking up post codes
[ERROR] Looking up post codes.Looking up US locations by post code #1  Time elapsed: 0.191 s  <<< ERROR!
java.lang.IllegalStateException: Failed to resolve the class file version of the current VM: Unknown Java version: 0

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   Failed to resolve the class file version of the current VM: Unknown Java version: 0
[INFO] 
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- serenity-maven-plugin:2.4.51:aggregate (serenity-reports) @ serenity-rest-starter ---
[INFO] Test results for 0 tests generated in 826 ms in directory: file:/Users/akashtyagi/Documents/vCodePostDec2023/personal/trainings/serenity-rest-starter/target/site/serenity/
[INFO] -----------------------------------------
[INFO]  SERENITY TESTS : SUCCESS
[INFO] -----------------------------------------
[INFO] | Tests executed         | 0
[INFO] | Tests passed           | 0
[INFO] | Tests failed           | 0
[INFO] | Tests with errors      | 0
[INFO] | Tests compromised      | 0
[INFO] | Tests pending          | 0
[INFO] | Tests ignored/skipped  | 0
[INFO] ------------------------ | --------------
[INFO] | Total Duration         | 000ms
[INFO] | Fastest test took      | 000ms
[INFO] | Slowest test took      | 000ms
[INFO] -----------------------------------------
[INFO] 
[INFO] SERENITY REPORTS
[INFO]   - Full Report: file:///Users/akashtyagi/Documents/vCodePostDec2023/personal/trainings/serenity-rest-starter/target/site/serenity/index.html
[INFO] 
[INFO] --- maven-failsafe-plugin:3.0.0-M5:verify (default) @ serenity-rest-starter ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.001 s
[INFO] Finished at: 2024-02-17T18:06:58+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:3.0.0-M5:verify (default) on project serenity-rest-starter: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/akashtyagi/Documents/vCodePostDec2023/personal/trainings/serenity-rest-starter/target/failsafe-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
serenity-rest-starter $ 



```
